fastlane_version "2.24.0"

default_platform :ios

ENV['SLACK_URL'] = "https://hooks.slack.com/services/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"


platform :ios do
   	lane :example do
      puts("this is my first 🚀 lane")

      slack(message: "Successfully deployed daily.")

   	end

	lane :deploy_daily do

		puts("this is deploy_daily")
		
	    ensure_git_status_clean
	    ensure_git_branch(branch: "master")

	    update_translations

	    cocoapods 

	    clean_build_artifacts

	    slack(message: "Successfully deployed daily.")

	    push_to_git_remote
	end

  error do |lane, exception|
     slack(message: exception.message, success: false)
  end

end
